import { Model, User } from '@/types'

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'yamada_3d',
    displayName: '山田太郎',
    bio: '3Dアーティスト。キャラクターモデリングが得意です。',
    avatarUrl: '',
    isPremium: true,
    followerCount: 1234,
    followingCount: 567,
    createdAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '2', 
    username: 'sato_artist',
    displayName: '佐藤花子',
    bio: '建築系3Dモデルを制作しています。',
    avatarUrl: '',
    isPremium: false,
    followerCount: 890,
    followingCount: 234,
    createdAt: '2024-02-01T00:00:00Z'
  },
  {
    id: '3',
    username: 'tanaka_cg',
    displayName: '田中次郎',
    bio: 'ゲーム用アセット制作。アニメーション付きモデル多数。',
    avatarUrl: '',
    isPremium: true,
    followerCount: 2456,
    followingCount: 123,
    createdAt: '2024-03-01T00:00:00Z'
  }
]

export const mockModels: Model[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    title: 'ファンタジーキャラクター - 騎士',
    description: '中世ファンタジー風の騎士キャラクターです。フルアーマー装備でリグ付き。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb',
    thumbnailUrl: '',
    hasAnimation: true,
    animationDuration: 5.2,
    licenseType: 'CC BY',
    isCommercialOk: true,
    price: 0,
    currency: 'JPY',
    isFree: true,
    viewCount: 15234,
    downloadCount: 3456,
    likeCount: 987,
    status: 'public',
    tags: ['キャラクター', 'ファンタジー', '騎士', 'アニメーション'],
    metadata: {},
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    polygonCount: 50000,
    fileSize: 12500000
  },
  {
    id: '2',
    userId: '2',
    user: mockUsers[1],
    title: '近代的なオフィスビル',
    description: '30階建ての近代的なオフィスビル。窓や内装の詳細まで作り込みました。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Sponza/glTF/Sponza.gltf',
    thumbnailUrl: '',
    hasAnimation: false,
    licenseType: 'CC BY-SA',
    isCommercialOk: true,
    price: 2500,
    currency: 'JPY',
    isFree: false,
    viewCount: 8765,
    downloadCount: 432,
    likeCount: 234,
    status: 'public',
    tags: ['建築', 'ビル', '都市', 'リアル'],
    metadata: {},
    createdAt: '2024-10-15T14:30:00Z',
    updatedAt: '2024-10-15T14:30:00Z',
    polygonCount: 120000,
    fileSize: 45000000
  },
  {
    id: '3',
    userId: '3',
    user: mockUsers[2],
    title: 'SFメカ - バトルロボット',
    description: '変形機能付きのバトルロボット。各部パーツが可動します。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF-Binary/BoxAnimated.glb',
    thumbnailUrl: '',
    hasAnimation: true,
    animationDuration: 8.5,
    licenseType: 'CC BY-NC',
    isCommercialOk: false,
    price: 5000,
    currency: 'JPY',
    isFree: false,
    viewCount: 23456,
    downloadCount: 1234,
    likeCount: 2345,
    status: 'public',
    tags: ['メカ', 'ロボット', 'SF', 'アニメーション'],
    metadata: {},
    createdAt: '2024-09-20T09:15:00Z',
    updatedAt: '2024-09-20T09:15:00Z',
    polygonCount: 80000,
    fileSize: 35000000
  },
  {
    id: '4',
    userId: '1',
    user: mockUsers[0],
    title: '魔法の杖コレクション',
    description: '10種類の魔法の杖セット。ゲーム用アイテムとして最適。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb',
    thumbnailUrl: '',
    hasAnimation: false,
    licenseType: 'CC BY',
    isCommercialOk: true,
    price: 0,
    currency: 'JPY',
    isFree: true,
    viewCount: 5678,
    downloadCount: 890,
    likeCount: 456,
    status: 'public',
    tags: ['武器', 'ファンタジー', 'アイテム', 'ローポリ'],
    metadata: {},
    createdAt: '2024-08-10T16:45:00Z',
    updatedAt: '2024-08-10T16:45:00Z',
    polygonCount: 5000,
    fileSize: 2500000
  },
  {
    id: '5',
    userId: '2',
    user: mockUsers[1],
    title: '日本庭園セット',
    description: '石灯籠、橋、池などを含む日本庭園の完全セット。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb',
    thumbnailUrl: '',
    hasAnimation: false,
    licenseType: 'CC BY-SA',
    isCommercialOk: true,
    price: 3500,
    currency: 'JPY',
    isFree: false,
    viewCount: 12345,
    downloadCount: 567,
    likeCount: 789,
    status: 'public',
    tags: ['建築', '日本', '庭園', '自然'],
    metadata: {},
    createdAt: '2024-07-25T11:20:00Z',
    updatedAt: '2024-07-25T11:20:00Z',
    polygonCount: 95000,
    fileSize: 38000000
  },
  {
    id: '6',
    userId: '3',
    user: mockUsers[2],
    title: 'サイバーパンク都市',
    description: 'ネオン輝くサイバーパンク風の都市景観。夜景シーン向け。',
    fileUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/CesiumMan/glTF-Binary/CesiumMan.glb',
    thumbnailUrl: '',
    hasAnimation: true,
    animationDuration: 12.0,
    licenseType: 'CC BY',
    isCommercialOk: true,
    price: 0,
    currency: 'JPY',
    isFree: true,
    viewCount: 34567,
    downloadCount: 2345,
    likeCount: 3456,
    status: 'public',
    tags: ['都市', 'サイバーパンク', 'SF', '建築'],
    metadata: {},
    createdAt: '2024-06-30T18:00:00Z',
    updatedAt: '2024-06-30T18:00:00Z',
    polygonCount: 250000,
    fileSize: 85000000
  }
]